name: Gitlab mirroring CI/CD process

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: 'Push the main branch to Gitlab'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to gitlab
        env:
          GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          GITLAB_URL_WITH_TOKEN=$(echo "$GITLAB_REPO_URL" | sed "s|://|://oauth2:$GITLAB_ACCESS_TOKEN@|")
          git push "$GITLAB_URL_WITH_TOKEN" main --force
          git push "$GITLAB_URL_WITH_TOKEN" --tags --force
